# Generated by Django 4.2.23 on 2025-08-12 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('min_requirements', models.TextField(blank=True, null=True)),
                ('max_requirements', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(upload_to='covers/')),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('download_link', models.URLField()),
                ('release_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.category')),
            ],
        ),
    ]
